[tool.bumpversion]
current_version = "0.0.0"

[[tool.bumpversion.files]]
filename = "services/frontend/package.json"
search = '"version": "{current_version}"'
replace = '"version": "{new_version}"'

# package-lock is replaced twice (mind the whitespaces)
[[tool.bumpversion.files]]
filename = "services/frontend/package-lock.json"
search = '''
  "name": "@uneos/service_extern_excercise1",
  "version": "{current_version}",
'''
replace = '''
  "name": "@uneos/service_extern_excercise1",
  "version": "{new_version}",
'''
[[tool.bumpversion.files]]
filename = "services/frontend/package-lock.json"
search = '''
      "name": "@uneos/service_extern_excercise1",
      "version": "{current_version}",
'''
replace = '''
      "name": "@uneos/service_extern_excercise1",
      "version": "{new_version}",
'''

[[tool.bumpversion.files]]
filename = "services/frontend/src/api/core/OpenAPI.ts"
search = "VERSION: '{current_version}',"
replace = "VERSION: '{new_version}',"

[[tool.bumpversion.files]]
filename = "services/frontend/chart/Chart.yaml"
search = "version: {current_version}"
replace = "version: {new_version}"


[[tool.bumpversion.files]]
filename = "services/backend/pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "services/backend/src/excers/_version.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.bumpversion.files]]
filename = "openapi_excers.yaml"
search = 'version: {current_version}'
replace = 'version: {new_version}'

[[tool.bumpversion.files]]
filename = "services/backend/chart/Chart.yaml"
search = "version: {current_version}"
replace = "version: {new_version}"
