version: "0.2"
dictionaries:
  - en
  - de-de
  - bash
  - css
  - dockerfile
  - k8s
  - python
  - typescript
dictionaryDefinitions: []
enableFiletypes:
  - dockerfile
ignorePaths:
  - .(git|docker)ignore
  - .gitmodules
  - .vscode
  - .devcontainer
  - cspell.config.yaml
words:
  - excers
  - excercise1
  - service_extern_excercise1
  - ADDPASSWORD
  - adduser
  - ADDUSER
  - anzeigen
  - appuser
  - autodocs
  - autoforwarded
  - axios
  - azurecr
  - bumpversion
  - codegen
  - dapr
  - debugpy
  - devcontainer
  - dockerconfigjson
  - dockerpath
  - fastapi
  - Favoriten
  - flowbite
  - forwardauth
  - gecos
  - groundnuty
  - gunicorn
  - keyscan
  - läuft
  - meauth
  - meflag
  - melogs
  - oidc
  - OIDC
  - Oixk
  - orderprocessing
  - orderpubsub
  - PGHOST
  - PGPASSWORD
  - PGUSER
  - pinia
  - Pinia
  - Prietz
  - psql
  - psycopg
  - PYTHONDONTWRITEBYTECODE
  - PYTHONUNBUFFERED
  - rabbitmq
  - rootdir
  - setuptools
  - starlette
  - Starlette
  - tailwindcss
  - testpaths
  - Tiltfile
  - traefik
  - uneos
  - unleashorg
  - uvicorn
  - Uvicorn
  - VITE
  - vueuse
  - webserver
  - WORKDIR
  - zipkin
