components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    User:
      properties:
        roles:
          items:
            type: string
          title: Roles
          type: array
        username:
          title: Username
          type: string
      required:
      - username
      title: User
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  contact:
    email: pablo.prietz@uneos.io
  description: '[service extern] excercise1'
  title: excers
  version: 0.0.0
openapi: 3.0.2
paths:
  /:
    get:
      operationId: home__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Home
  /login:
    get:
      operationId: login_login_get
      parameters:
      - in: query
        name: after_login
        required: false
        schema:
          title: After Login
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '302':
          description: Redirecting to authentication server
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
        '504':
          description: Authentication server timed out
      summary: Login
      tags:
      - auth
  /user:
    get:
      operationId: get_current_user_user_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Successful Response
        '401':
          description: User unauthorized or authentication problem
      summary: Get Current User
      tags:
      - auth
