apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SESSION_SECRET_KEY: a45af3d442a96c635e9783bac73381287fbef3c87a95a02cacdcdfe9dc08a9ed
  OIDC_CLIENT_ID: ba007a20-dde8-413f-ae51-c2d3a8910884
  OIDC_CLIENT_SECRET: aN0CT1zIckYz3nl9gQQE1us7UFpLh0bE4IHxrAVkAvM
  DATABASE_CONNECTION_STRING: postgresql+psycopg2://{{ .Chart.Name }}-{{ .Values.namespace }}-user:{{ .Values.backend_pass }}@sepost:5432/{{ .Chart.Name }}-{{ .Values.namespace }}-user
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-init-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  PGUSER: admin-{{ .Values.namespace }}
  PGPASSWORD: {{ .Values.db_pass }}
  ADDPASSWORD: {{ .Values.backend_pass }}
  ADDUSER: {{ .Chart.Name }}-{{ .Values.namespace }}-user
